import {
    RUN_CYCLE_OPTIONS,
    WEEK_DAY_OPTIONS,
    MONTH_DAY_OPTIONS,
} from '@/utils/scheduleUtil.ts'

const addConfig = {
    pageName: 'task',
    title: '接口自动化任务',
    formItem: [
        {
            type: 'input',
            label: '任务ID',
            prop: 'id',
            initialValue: null,
            disabled: true,
            isIndex: true,
        },
        {
            type: 'input',
            label: '任务名',
            placeholder: '请输入任务名',
            prop: 'name',
            initialValue: null,
            isIndex: false,
        },
        {
            type: 'select',
            label: '可选任务',
            placeholder: '请选择任务',
            prop: 'task',
            pageName: 'getTask',
            key: 'taskCode',
            value: 'taskName',
            initialValue: '',
            isIndex: false,
        },
        {
            type: 'suitArgs',
            label: '执行套件',
            placeholder: '请选择套件',
            prop: 'suitIds',
            submitProp: 'args',
            pageName: 'suit',
            key: 'suitId',
            value: 'suitName',
            multiple: true,
            initialValue: [],
            isIndex: false,
        },
        {
            type: 'input',
            label: '选填参数',
            placeholder: '选填参数',
            prop: 'kwargs',
            initialValue: {},
            isIndex: false,
        },
        {
            type: 'input',
            label: 'QMQ请求头',
            placeholder: '请输入',
            prop: 'headers',
            initialValue: null,
            isIndex: false,
        },
        {
            type: 'radio',
            label: '运行周期',
            placeholder: '请选择运行周期',
            prop: 'runCycleType',
            options: RUN_CYCLE_OPTIONS,
            key: 'value',
            value: 'label',
            initialValue: 'daily',
            isIndex: false,
        },
        {
            type: 'timeOnly',
            label: '运行时间',
            placeholder: '请选择运行时间',
            prop: 'runTime',
            initialValue: '09:00:00',
            isIndex: false,
            showWhen: { runCycleType: 'daily' },
        },
        {
            type: 'radio',
            label: '运行日',
            placeholder: '请选择星期',
            prop: 'runWeekDay',
            options: WEEK_DAY_OPTIONS,
            key: 'value',
            value: 'label',
            initialValue: '1',
            isIndex: false,
            showWhen: { runCycleType: 'weekly' },
        },
        {
            type: 'timeOnly',
            label: '运行时间',
            placeholder: '请选择运行时间',
            prop: 'runTime',
            initialValue: '09:00:00',
            isIndex: false,
            showWhen: { runCycleType: 'weekly' },
        },
        {
            type: 'select',
            label: '运行日期',
            placeholder: '请选择日期',
            prop: 'runMonthDay',
            options: MONTH_DAY_OPTIONS,
            key: 'value',
            value: 'label',
            initialValue: '1',
            isIndex: false,
            showWhen: { runCycleType: 'monthly' },
        },
        {
            type: 'timeOnly',
            label: '运行时间',
            placeholder: '请选择运行时间',
            prop: 'runTime',
            initialValue: '09:00:00',
            isIndex: false,
            showWhen: { runCycleType: 'monthly' },
        },
        {
            type: 'input',
            label: 'Cron 表达式',
            placeholder: '5段格式：分 时 日 月 周，例如 0 9 * * *',
            prop: 'cronExpression',
            initialValue: '0 9 * * *',
            isIndex: false,
            showWhen: { runCycleType: 'custom' },
        },
        {
            type: 'time',
            label: '生效开始',
            placeholder: '可选',
            prop: 'start_time',
            initialValue: null,
            isIndex: false,
        },
        {
            type: 'time',
            label: '生效结束',
            placeholder: '可选',
            prop: 'expires',
            initialValue: null,
            isIndex: false,
        },
        {
            type: 'single',
            label: '仅执行一次',
            prop: 'one_off',
            placeholder: '请选择',
            initialValue: false,
            isIndex: false,
        },
        {
            type: 'single',
            label: '是否执行',
            placeholder: '请选择',
            prop: 'enabled',
            initialValue: true,
            isIndex: false,
        },
    ],
    search: {
        cascade: {
            depart: true,
            apply: true,
            port: true,
            httpcase: true,
        },
    },
    rules: {
        task: [{ required: true, message: '执行JOB不可为空', trigger: 'blur' }],
        name: [{ required: true, message: '任务名必填', trigger: 'blur' }],
        runCycleType: [{ required: true, message: '请选择运行周期', trigger: 'change' }],
        suitIds: [
            {
                required: true,
                type: 'array',
                min: 1,
                message: '请至少选择一个套件',
                trigger: 'change',
            },
        ],
    },
}

export default addConfig